server:
  port: 8080

spring:
  application:
    name: chat-gateway

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: chat-gateway
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.mateusdomelo.chatgateway.messaging.event.ChatReplyEvent
        spring.json.trusted.packages: "com.mateusdomelo.*"

  data:
    mongodb:
      uri: mongodb://localhost:27017/chatbot

app:
  topics:
    messages: chat.messages
    replies: chat.replies
  security:
    username: ${CHAT_GATEWAY_USER}
    password: ${CHAT_GATEWAY_PASSWORD}

logging:
  level:
    com.mateusdomelo: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: never
